name: esptouch_flutter
description: Flutter plugin for ESP-Touch (Smart Config) to configure network for ESP-8266 and ESP-32 devices. Runs on iOS and Android.
version: 2.0.2
homepage: https://github.com/smaho-engineering/esptouch_flutter

environment:
  sdk: '>=3.10.3 <4.0.0'
  flutter: '>=3.38.7'

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.smaho.eng.esptouch
        pluginClass: EsptouchPlugin
      ios:
        pluginClass: EsptouchPlugin
